

Error 07/05/2024:
Traceback (most recent call last):
  File "c:\Users\prann\OneDrive - Cabarrus County Schools\Python 1 Code\final project\main.py", line 51, in <module>
    pages[selection - 1]()
    ~~~~~^^^^^^^^^^^^^^^
IndexError: list index out of range

    
NoneType: None
